### ISSUE TITLE
Figure out how to parse JSON into the `prepublish` process

### ISSUE THREAD

**Issue by gabidavila** [gabidavila/react-usa-map#12]
The file [usa-map-dimensions.js](https://github.com/gabidavila/react-usa-map/blob/master/src/data/usa-map-dimensions.js) in the beginning of developing this package was supposed to be a `usa-map-dimensions.json`. Right now I am doing a workaround declaring the data as a javascript constant, however I think architecturally speaking this is better since JSON purpose is to store data.

**Comment by kytwb** [comment]
Going for it.

**Comment by kytwb** [comment]
Looks like someone was already working on it and submitted a PR. Nevermind :sweat_smile:
