### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by gabidavila** [gabidavila/react-usa-map#4]
Travis CI, Circle CI, any of it :)

**Comment by bossbossk20** [comment]
I did it @gabidavila

**Comment by gabidavila** [comment]
Thank you @bossbossk20 , I am gonna add `npm test` to the script, or you can add it :) 👍

**Comment by bossbossk20** [comment]
@gabidavila  I will add for you

**Comment by CodingFrieda** [comment]
What do you think of code quality tools like [CODEBEAT](https://codebeat.co/) or [Code Climate](https://codeclimate.com/) @gabidavila @bossbossk20?
