### ISSUE TITLE
Fix event handler for DC

### ISSUE THREAD

**Issue by gabidavila** [gabidavila/react-usa-map#5]
Currently when you click on DC it returns `undefined`.

**Comment by Frewacom** [comment]
If I am not misstaken, you have forgotten to create a data element which contains DC's dimensions, abbreviation and name in src/data/usa-map-dimensions.js

I'm not sure how you get the dimensions of the states, so I can't fork and fix it.

**Comment by gabidavila** [comment]
I got it fixed, but now I am breaking the tests 😅 . The `onClick` was on the wrong place also.

I Didnt exactly forget about `DC` there, because it has its own svg `g` tag, I may have to move that around.

Thanks @Frewacom  :)

**Comment by Frewacom** [comment]
@gabidavila Oh, I see. Glad you got it fixed at least.
